### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by linuxtrainer** [anfractuosity/usbmeter#1]
If I use the script for my new UM25C, I always get:
```
leo@uranus:~/Downloads/usbmeter-master$ ./usbmeter.py 
Found 00:15:A3:00:19:F1
Traceback (most recent call last):
  File "./usbmeter.py", line 35, in <module>
    first_match = service_matches[0]
IndexError: list index out of range
```
I am working on Ubuntu 16.04.6 LTS !
Are there any solutions? Thanks for help and best regards!
Leo

**Comment by anfractuosity** [comment]
Thanks for the bug report.  I've not had that issue myself I'm afraid. I'm just wondering if you could clone the repo again, I just made a little change, if you could tell me what that prints, that would be great.

Cheers

**Comment by linuxtrainer** [comment]
THX for your answer. 
Error the same with last version.
I think there is a connection problem. 
I tested your program with my UM24C and there is no problem. All works well.

But the UM25C has sometimes connection-problems and the message

> first_match = service_matches[0]
> IndexError: list index out of range

is also generated if there is no UM25C connected.
Interesestingly I have no problem using rdserialtool: https://pypi.org/project/rdserialtool/
Thx for your program and your time!
best regards
Leo

**Comment by anfractuosity** [comment]
Thanks.  The new commit will fix that list index error.
